services:
  - type: web
    name: ai-trader-backtest
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --graceful-timeout 300
    envVars:
      - key: APP_USERNAME
        sync: false
      - key: APP_PASSWORD
        sync: false
